<?php

/**
 * @file
 * Module file for Domain access sitemap module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function domain_simple_sitemap_domain_insert(EntityInterface $domain) {
  // Regenerate sitemap on add/edit/delete new domain.
  \Drupal::service('simple_sitemap.generator')->generateSitemap();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function domain_simple_sitemap_domain_update(EntityInterface $domain) {
  if ($domain->status() !== $domain->get('original')->status()) {
    domain_simple_sitemap_domain_insert($domain);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function domain_simple_sitemap_domain_delete(EntityInterface $domain) {
  domain_simple_sitemap_domain_insert($domain);
}
